### PR TITLE
Create CHANGELOG.md

### PR DESCRIPTION
**Pull request by ZeeCoder**
I've been ignoring updates to this project, as there's no easy way to tell what changed in any given version.
To help myself and potentially others, I propose adding the following changelog to the project.

Some advise in terms of maintaining the changelog:
- All meaningful features / patches should make their way under the [Unreleased] section, so that once it's time to release it's easy to move everything under whatever release version you've chosen.
- When you choose a release version, pay attention to the changes you have under the unreleased section: if there's anything "Added", then it's a minor version bump. If there are breaking changes, it's major, and otherwise patch is sufficient.
- Make sure PRs include changes under [Unreleased]. This again will make your job easier, and also signals to people looking at the master branch's changelog that those features are about to be released.

 Hope you find this useful. 👍

### CODE REVIEW

**Comment by Mottie** [comment]
And in the main readme, I show the 3 most [recent changes](https://github.com/Mottie/Keyboard#change-log).

**Comment by ZeeCoder** [comment]
Yes that wiki changelog is excactly what I would've wanted!
I think it would be better to keep it in the file though, or maybe just a link to the wiki? Not sure.
It's kind of standard to keep a changelog file, so people will definitely look there and are not guaranteed to find it on the wiki.
Or in the main readme either, it wouldn't have occurred to me that you have notes at the bottom. 😅

**Comment by Mottie** [comment]
Yeah, I didn't add a `CHANGELOG.md` because I've never liked all the clutter in the root folder. I wish I could move all the dot files and stuff into a sub-folder.

I guess I could add a `CHANGELOG.md` file that points to the wiki page, to save me the trouble of moving stuff around.

**Comment by ZeeCoder** [comment]
Yeah, that's perfectly fine with me 👍

**Comment by Mottie** [comment]
Done 😸

**Comment by ZeeCoder** [comment]
🎉 Awesome, thanks!

**Pull request closed without merging**
