### PR TITLE
Introduce Korean language

### PR DESCRIPTION
**Pull request by Poitrin**
**Addresses issues #624 and #539.**

In Korean language, a hangul syllable (“letter”) can be decomposed into 2 (Initial + Medial) or 3 (Initial + Medial + Final / Choseong, Jungseong, and Jongseong) parts:
1. `ᄂ` (`U+1102`) + `ᅡ` (`U+1161`) = `나` (`U+B098`)
2. `ᄋ` (`U+110B`) + `ᅡ` (`U+1161`) + `ᆫ` (`U+11AB`) = `안` (`U+C548`)

`ㄴ` looks the same in both examples, but has a different meaning.
In 1., it’s the _initial_, in 2., it’s the _final_ part.

At the moment, the greywyvern keyboard uses `U+1102`, so that only example 1 can be composed. If `U+1102` would switch to `U+11AB` while typing, example 2 could be composed too.

Based on [this definition](https://en.wikipedia.org/wiki/Korean_language_and_computers#Hangul_in_Unicode), this PR adds logic to replace medial + initial combinations with medial + final combinations. For example 2, this means that `ᅡ` (`U+1161`)  + `ᄂ` (`U+1102`) would be replaced by `ᅡ` (`U+1161`) + `ᆫ` (`U+11AB`).

### Caveats
- See https://github.com/Mottie/Keyboard/issues/539#issuecomment-383739329: _Some work would need to be done probably to handle spaces, the delete key and user experience type things. For example, a string of characters might be ambiguous but a space can be used to be specific_.
- Translations have been done with Google Translate.
- Files in `dist` _that I haven't changed_ would need to be updated too.

### CODE REVIEW

**Comment by Mottie** [comment]
Hey @Poitrin!

Thanks so much for all your hard work 🎉. I will try to look at this PR when I get some free time.

**Comment by Poitrin** [comment]
I got feedback from a Korean speaker, and he told me that the keyboard does not behave as expected. I explained it here: https://github.com/Mottie/Keyboard/issues/539#issuecomment-572113709

Since we'd need more logic to implement Korean language correctly, I'm going to close this PR.

**Comment by Poitrin** [comment]
NB, for all others having the same problem: We included https://github.com/e-/Hangul.js, and disassemble + (re)assemble the whole input, at each keypress. As indicated in one of the issue’s comments, I don’t know if 3rd-party-libraries will be allowed to be included in the future.

**Comment by Mottie** [comment]
That should be possible now, using the [`beforeInsert`](https://github.com/Mottie/Keyboard/wiki/Methods#beforeinsert) callback, but then the main issue becomes where to place the caret after the content changes.

**Pull request closed without merging**
