### PR TITLE
New setting "closeByClickEvent" implemented 

### PR DESCRIPTION
**Pull request by SeeeD**
The new setting "closeByClickEvent" should prevent closing the keyboard on "touchstart" and "mousedown". 
This will allow the user to scroll the user during the keyboard is open.

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @SeeeD!

Hmm, I was going to say that the `userClosed` option should do the same thing as this and point to the documentation, but it appears I never added it to the docs!

Please try the demo mentioned here: https://github.com/Mottie/Keyboard/issues/415#issuecomment-174198661

If that behaves the same as this option, please let me know.

**Comment by SeeeD** [comment]
Hi @Mottie, 

thanks for you reply. I will have a look if this option will do the trick. :+1:

**Comment by Mottie** [comment]
Thanks! And I just finished adding the option to the docs: https://github.com/Mottie/Keyboard/wiki/Usability#userclosed

**Comment by SeeeD** [comment]
Hi @Mottie,
this does not work for me. :( 
If I am testing the jsfiddle linked in #415 I will get the same issue. Clicking outside should close the keyboard, but scrolling should be possible too on touch mode (I am using this keyboard on a touch-device without built in keyboard).

**Comment by Mottie** [comment]
Hmm, ok. I'll look into this when I get some time later today.

**Comment by Mottie** [comment]
Ok, I'll go ahead and add this option. Thanks!

**Pull request merged**
