### PR TITLE
Update russian.js

### PR DESCRIPTION
**Pull request by ihsoft**
- Access language settings via a dictionary key instead of object property.
- Change "alt" to the same caption as Russian Windows 8 shows (RUS: Russian keyboard).
- Translate "Accept/Cancel/Change sign" since these captions are not commonly recognized in Russian.
- Translate "Space" since in most virtual keyboards it's translated as "Пробел".

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @ihsoft! Thanks!

**Comment by ihsoft** [comment]
You're welcome :) It's a great plugin! Unfortunately, I had stop using it in my project because of jQuery UI + keyboard is extremly slow on the target device (LG SmartTV 2012): a dialog with vitual keyboard controls opens 5-6 seconds :( I've spent hours tyring to figure out why but eventually gave up.

Though, I used your ideas in my own simplified solution (pure jQuery, minimal functionality) and decided to keep compatibility with the Mottie Keyboard layout files because I see them doing the job very well. Why inventing the wheel, right? :)

**Comment by Mottie** [comment]
jQuery UI is an optional dependency. The default plugin uses the jQuery UI theme & position utility, but neither are needed if you modify the class definitions (see the Bootstrap demo on the main page), and position the keyboard manually.

Alternatively, you could build a [custom version of jQuery UI](http://jqueryui.com/download/#!version=1.11.4&components=1111000000000000000000000000000000000) with only the stylesheet & position utility.

**Comment by ihsoft** [comment]
Well, I don't remember for sure what was the problem but when I ran keyboard w/o UI it was awful. Basically, that's how UI appeared in my project in the first place. Now I think it was a wrong idea, and I'm going to remove UI dependencies despite of the convenience they offer. When you run a 1Ghz single core processor with 1Gb of memory things look different.

**Comment by Mottie** [comment]
> when I ran keyboard w/o UI it was awful

What do you mean? Is there a specific issue that needs to be addressed?

I made [this demo](http://jsfiddle.net/MK947/3837/) which is using a Bootstrap theme without jQuery UI loaded. It doesn't look too bad to me, but I am a bit biased :wink:

**Pull request merged**
